# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e0qM1dXy3WXkcN9QXFXR-Ywn3_suyl5
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install mediapipe opencv-python pandas tqdm

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohamadashrafsalama/pushup")

print("Path to dataset files:", path)

import os

# Use the path obtained from kagglehub.dataset_download from the previous cell
BASE_DATASET_ROOT = path

video_folders = []
# The dataset has two main subdirectories containing videos: 'Correct sequence' and 'Wrong sequence'
expected_video_subdirs = ['Correct sequence', 'Wrong sequence']

for sub_dir_name in expected_video_subdirs:
    current_videos_dir = os.path.join(BASE_DATASET_ROOT, sub_dir_name)
    if os.path.isdir(current_videos_dir):
        video_folders.append(current_videos_dir)
    else:
        print(f"Warning: Expected video directory '{current_videos_dir}' not found.")

all_videos = []
for folder in video_folders:
    for file in os.listdir(folder):
        if file.lower().endswith(('.mp4', '.avi', '.mov', '.mkv')): # Added .mkv for completeness
            all_videos.append(os.path.join(folder, file))

print("Total videos found:", len(all_videos))
print(all_videos[:5])

!pip install mediapipe opencv-python pandas tqdm

# المكتبات
import cv2, os, csv
from tqdm import tqdm
import mediapipe as mp # Keep this for mp.solutions.drawing_utils
import mediapipe.solutions # Explicitly import the solutions sub-package

mp_pose = mp.solutions.pose

# Base path for the downloaded dataset
BASE_DATASET_DIR = '/root/.cache/kagglehub/datasets/mohamadashrafsalama/pushup/versions/1'
OUTPUT_CSV = '/content/dataset/landmarks.csv' # Ensure '/content/dataset' exists or create it

# Create the output directory if it doesn't exist
os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)

# إعداد CSV header
n_landmarks = 33  # MediaPipe Pose
header = ['video_name', 'frame_index', 'label', 'detected']
for i in range(n_landmarks):
    header += [f'x_{i}', f'y_{i}', f'z_{i}', f'vis_{i}']

with open(OUTPUT_CSV, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

    # Define the subdirectories containing the videos and their corresponding labels
    video_subdirs = {
        'Correct sequence': 'correct_pushup',
        'Wrong sequence': 'wrong_pushup'
    }

    # نفّذ على كل فيديو في كل مجلد
    for sub_dir_name, label_prefix in video_subdirs.items():
        current_videos_dir = os.path.join(BASE_DATASET_DIR, sub_dir_name)

        if not os.path.isdir(current_videos_dir):
            print(f"Warning: Directory '{current_videos_dir}' not found. Skipping.")
            continue

        for fname in os.listdir(current_videos_dir):
            if not fname.lower().endswith(('.mp4', '.avi', '.mov', '.mkv')):
                continue
            video_path = os.path.join(current_videos_dir, fname)
            label = label_prefix # Use the label based on the subdirectory
            cap = cv2.VideoCapture(video_path)
            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

            if total_frames == 0:
                print(f"Warning: No frames found in {video_path}. Skipping.")
                cap.release()
                continue

            with mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5) as pose:
                frame_idx = 0
                pbar = tqdm(total=total_frames, desc=f"{label_prefix}/{fname}")
                while True:
                    ret, frame = cap.read()
                    if not ret:
                        break
                    # optional: sample frames, e.g., if frame_idx % 2 != 0: continue
                    image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    results = pose.process(image_rgb)

                    row = [fname, frame_idx, label, 0]  # detected flag default 0
                    if results.pose_landmarks:
                        row[3] = 1
                        for lm in results.pose_landmarks.landmark:
                            row += [lm.x, lm.y, lm.z, lm.visibility]
                    else:
                        # add placeholders for undetected poses
                        for _ in range(n_landmarks):
                            row += [None, None, None, None]

                    writer.writerow(row)
                    frame_idx += 1
                    pbar.update(1)
                pbar.close()
            cap.release()

import pandas as pd

df = pd.read_csv("/content/dataset/landmarks.csv")
df.head()

df = df.drop(columns=["video_name", "frame_index", "detected"])

X = df.drop(columns=["label"])
y = df["label"]

df.isnull().sum()

df.dropna

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))



import pickle
with open('pushup_model.pkl','wb') as f:
    pickle.dump(model, f)

import cv2
import mediapipe as mp
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from collections import deque

# ----------------------
# 1️⃣ Load your trained model
# ----------------------
# لو خزنتيه باستخدام pickle:
import pickle
with open('pushup_model.pkl', 'rb') as f:
    model = pickle.load(f)

# ----------------------
# 2️⃣ Initialize MediaPipe Pose
# ----------------------
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5)

# ----------------------
# 3️⃣ Real-time smoothing
# ----------------------
queue_size = 5
pred_queue = deque(maxlen=queue_size)

# ----------------------
# 4️⃣ Open webcam
# ----------------------
cap = cv2.VideoCapture(0)  # 0 = default webcam

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Flip image horizontally for natural selfie view
    frame = cv2.flip(frame, 1)

    # Convert BGR to RGB
    img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Process frame
    results = pose.process(img_rgb)

    # Prepare landmarks for model
    landmarks_list = []
    if results.pose_landmarks:
        for lm in results.pose_landmarks.landmark:
            landmarks_list += [lm.x, lm.y, lm.z, lm.visibility]
        # Predict
        pred = model.predict([landmarks_list])[0]
    else:
        pred = "No person detected"

    # ----------------------
    # Smoothing predictions
    # ----------------------
    pred_queue.append(pred)
    if len(pred_queue) == queue_size:
        # Most frequent prediction in last N frames
        smoothed_pred = max(set(pred_queue), key=pred_queue.count)
    else:
        smoothed_pred = pred

    # ----------------------
    # Draw prediction on frame
    # ----------------------
    cv2.putText(frame, f'Prediction: {smoothed_pred}', (30,50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)

    # Draw landmarks
    if results.pose_landmarks:
        mp.solutions.drawing_utils.draw_landmarks(
            frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

    # Show frame
    cv2.imshow("Pushup Detection", frame)

    # Break on 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

import cv2
from google.colab.patches import cv2_imshow

video = cv2.VideoCapture("/content/How to push up ✅.mp4")

while True:
    ret, frame = video.read()
    if not ret:
        break

    cv2_imshow(frame) # Changed from cv2.imshow

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

mp_hands = mp.solutions.hands
hands = mp_hands.Hands()
mp_drawing = mp.solutions.drawing_utils

video = cv2.VideoCapture("/content/How to push up ✅.mp4")

while True:
    ret, frame = video.read()
    if not ret:
        break

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = hands.process(frame_rgb)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)

    cv2_imshow(frame) # Changed from cv2.imshow

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

